config/routes.rb
Rails.application.routes.draw do
  resources :code_namespaces, only: [:show, :index]
  resources :folders, only: [:show]
  
  # resources :impl_calls
  # resources :preprocessor_lines
  # resources :variables
  resources :code_methods
  # resources :structures
  resources :code_classes, path: "classes"
  resources :code_files
  
  resources :projects do
    resources :display_boxes, only: [:index]
    resources :display_box_links, only: [:index]
  end
  
  resources :users
  
  root "welcome#index"
  
end

app/models/code_method.rb
class CodeMethod < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many :impl_calls, dependent: :destroy, foreign_key: "caller_id"
  has_many :method_calls, through: :impl_calls,  source: :called
  
  has_many :inverse_callings, dependent: :nullify, class_name: "ImplCall", foreign_key: "called_id"  
  has_many :called_by, through: :inverse_callings, source: :caller
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :impl_start, numericality: {greater_than_or_equal_to: 1 }
  validates :impl_end,   numericality: {greater_than_or_equal_to: 1 }
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/controllers/code_methods_controller.rb
class CodeMethodsController < ApplicationController
  before_action :set_code_method, only: [:show, :edit, :update, :destroy]

  # GET /code_methods
  # GET /code_methods.json
  def index
    @code_methods = CodeMethod.all
  end

  # GET /code_methods/1
  # GET /code_methods/1.json
  def show
  end

  # GET /code_methods/new
  def new
    @code_method = CodeMethod.new
  end

  # GET /code_methods/1/edit
  def edit
  end

  # POST /code_methods
  # POST /code_methods.json
  def create
    @code_method = CodeMethod.new(code_method_params)

    respond_to do |format|
      if @code_method.save
        format.html { redirect_to @code_method, notice: 'Code method was successfully created.' }
        format.json { render :show, status: :created, location: @code_method }
      else
        format.html { render :new }
        format.json { render json: @code_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_methods/1
  # PATCH/PUT /code_methods/1.json
  def update
    respond_to do |format|
      if @code_method.update(code_method_params)
        format.html { redirect_to @code_method, notice: 'Code method was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_method }
      else
        format.html { render :edit }
        format.json { render json: @code_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_methods/1
  # DELETE /code_methods/1.json
  def destroy
    @code_method.destroy
    respond_to do |format|
      format.html { redirect_to code_methods_url, notice: 'Code method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_method
      @code_method = CodeMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_method_params
      params.require(:code_method).permit(:name, :type, :arguments, :code_file_id, :code_class_id, :impl_start, :impl_end)
    end
end

app/helpers/code_methods_helper.rb
# require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/file_reader.rb"
require "/Users/darrylclarke/prj/clarity/lib/tasks/lib/tools.rb"
module CodeMethodsHelper
	
	def get_code_for_method( method )
		f = FileReader.new
		if method.code_file.name =~ /\.h\z/
			lines = f.get_range_in_file( method.code_file.path, method.impl_start, method.impl_end )
		else	
			start_pos = method.signature_line || method.impl_start
			
			lines = f.get_range_in_file( method.code_file.path, start_pos, method.impl_end+1 )
		end
		output = String.new
		# NEWLINE = "\r\n"
		lines.each do |line|
			output += "#{line.line.r_just}#{line.text}\r\n"
		end
		output
	end
end

app/views/code_methods/_form.html.erb
<%= form_for(@code_method) do |f| %>
  <% if @code_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_method.errors.count, "error") %> prohibited this code_method from being saved:</h2>

      <ul>
      <% @code_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :return_type %><br>
    <%= f.text_field :return_type %>
  </div>
  <div class="field">
    <%= f.label :arguments %><br>
    <%= f.text_field :arguments %>
  </div>
  <div class="field">
    <%= f.label :code_file_id %><br>
    <%= f.text_field :code_file_id %>
  </div>
  <div class="field">
    <%= f.label :code_class_id %><br>
    <%= f.text_field :code_class_id %>
  </div>
  <div class="field">
    <%= f.label :impl_start %><br>
    <%= f.number_field :impl_start %>
  </div>
  <div class="field">
    <%= f.label :impl_end %><br>
    <%= f.number_field :impl_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_methods/edit.html.erb
<h1>Editing Code Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_method %> |
<%= link_to 'Back', code_methods_path %>

app/views/code_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Code Methods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Arguments</th>
      <th>Code file</th>
      <th>Code class</th>
      <th>Impl start</th>
      <th>Impl end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @code_methods.each do |code_method| %>
      <tr>
        <td><%= code_method.name %></td>
        <td><%= code_method.return_type %></td>
        <td><%= code_method.arguments %></td>
        <td><%= code_method.code_file %></td>
        <td><%= code_method.code_class %></td>
        <td><%= code_method.impl_start %></td>
        <td><%= code_method.impl_end %></td>
        <td><%= link_to 'Show', code_method %></td>
        <td><%= link_to 'Edit', edit_code_method_path(code_method) %></td>
        <td><%= link_to 'Destroy', code_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code method', new_code_method_path %>

app/views/code_methods/new.html.erb
<h1>New Code Method</h1>

<%= render 'form' %>

<%= link_to 'Back', code_methods_path %>

app/views/code_methods/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 class="clarity-h1"><%= image_tag "f_method_icon.png", class: "element-icon" %> Method: <%= @code_method.name %></h1>
<div class="clarity-detail-box">
  <p>
    <strong>Return Type:</strong>
    <%= @code_method.return_type %>
  </p>
  
  <p>
    <strong>Arguments:</strong>
    <%= @code_method.arguments %>
  </p>
  
  <p>
    <% if @code_method.code_class %>
      <strong>Code class:</strong>
      <%= link_to @code_method.code_class.name, code_class_path( @code_method.code_class)  %>
    <% end %>
  </p>
  
  <p>
    <strong>File:</strong>
    <%= link_to @code_method.code_file.name, code_file_path( @code_method.code_file ) %>
    Lines <%= @code_method.impl_start %> to <%= @code_method.impl_end %>
  </p>
</div>

<h2 class="clarity-h2">Implementation:</h2>
<pre><code><%= get_code_for_method( @code_method ) %></code></pre>

<%= link_to "Display entire file", code_file_path(@code_method.code_file) + "?display=all#code-file-show-page-code-block", 
          class: "btn btn-info", 
          style: "float: right; margin-right: 15px;" 
          %>
<!--<pre>
  <code>
   <% if @code_method.code_class %>

std::unique_ptr&lt;EmulatorWindow&gt; <%= link_to "EmulatorWindow", code_class_path(@code_method.code_class), class: "clarity-link clarity-link-class" %>::Create(Emulator* emulator) {
  std::unique_ptr&lt;EmulatorWindow&gt; emulator_window(new EmulatorWindow(emulator));
<% end %>
  emulator_window->loop()-><%= link_to "PostSynchronous", code_method_path(12075), class: "clarity-link clarity-link-method" %>[&emulator_window]() {
  </code>
</pre>-->

<!--<%#= link_to 'Edit', edit_code_method_path(@code_method) %> |
<%#= link_to 'Back', code_methods_path %>-->