config/routes.rb
Rails.application.routes.draw do
  resources :code_namespaces, only: [:show, :index]
  resources :folders, only: [:show]
  
  # resources :impl_calls
  # resources :preprocessor_lines
  # resources :variables
  resources :code_methods
  # resources :structures
  resources :code_classes, path: "classes"
  resources :code_files
  
  resources :projects do
    resources :display_boxes, only: [:index]
    resources :display_box_links, only: [:index]
  end
  
  resources :users
  
  root "welcome#index"
  
end

app/models/code_class.rb
class CodeClass < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many   :code_methods
  has_many   :variables
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_file.rb
class CodeFile < ActiveRecord::Base
  belongs_to :project
  belongs_to :folder
  has_many   :code_methods, dependent: :destroy
  has_many   :variables, dependent: :destroy
  has_many   :code_classes, dependent: :destroy
  
  validates :name, presence: true
  validates :path, presence: true
  validates :project_id, presence: true
end

app/models/code_method.rb
class CodeMethod < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many :impl_calls, dependent: :destroy, foreign_key: "caller_id"
  has_many :method_calls, through: :impl_calls,  source: :called
  
  has_many :inverse_callings, dependent: :nullify, class_name: "ImplCall", foreign_key: "called_id"  
  has_many :called_by, through: :inverse_callings, source: :caller
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :impl_start, numericality: {greater_than_or_equal_to: 1 }
  validates :impl_end,   numericality: {greater_than_or_equal_to: 1 }
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_namespace.rb
class CodeNamespace < ActiveRecord::Base

belongs_to :project

end

app/models/display_box.rb
class DisplayBox < ActiveRecord::Base
  belongs_to :folder
  
  # has_many :linked_boxes, dependent: :destroy, foreign_key: "parent_id"
  # has_many :children, through: :linked_boxes,  source: :display_box
  
  # has_many :inverse_ownerships, dependent: :nullify, class_name: "DisplayBoxLine", foreign_key: "display_box_id"  
  # has_many :linked_by, through: :inverse_ownerships, source: :parent
end

app/models/display_box_line.rb
class DisplayBoxLine < ActiveRecord::Base
   # belongs_to :parent, class_name: "DisplayBox"
   # belongs_to :display_box, class_name: "DisplayBox"
end

app/models/display_box_link.rb
class DisplayBoxLink < ActiveRecord::Base
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :projects
  
  has_many :sub_folders, dependent: :destroy, foreign_key: "parent_id"
  has_many :children, through: :sub_folders,  source: :folder
  
  has_many :inverse_ownerships, dependent: :nullify, class_name: "SubFolder", foreign_key: "folder_id"  
  has_many :owned_by, through: :inverse_ownerships, source: :parent
  
  	
  has_many :code_files,  dependent: :nullify
  has_one  :display_box, dependent: :nullify
  
  
  def contained_files_alphabetically 
    code_files.order(:name)
  end
end

app/models/impl_call.rb
class ImplCall < ActiveRecord::Base
	belongs_to :caller, class_name: "CodeMethod"
	belongs_to :called, class_name: "CodeMethod"
	
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :user_projects, dependent: :nullify
  has_many :contributing_users, through: :user_projects, source: :user
  
  has_many :code_files,      dependent: :destroy
  has_many :folders,         dependent: :destroy
  has_many :code_namespaces, dependent: :destroy
  has_many :code_classes,    dependent: :destroy 
  has_many :code_methods,    dependent: :destroy 
  has_many :variables,       dependent: :destroy 
  
  validates :name,      presence: true#, uniqueness: true
  validates :root_path, presence: true#, uniqueness: true

end

app/models/structure.rb
class Structure < ActiveRecord::Base
  belongs_to :code_file
end

app/models/sub_folder.rb
class SubFolder < ActiveRecord::Base
  belongs_to :parent, class_name: "Folder"
  belongs_to :folder, class_name: "Folder"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password  
	
	has_many :user_projects, dependent: :nullify
	has_many :projects, through: :user_projects, source: :project 
	
	validates :first_name, presence: true

    # password must be there and password_confirmation has to match
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates	:email, presence: true, uniqueness: true,
						format: VALID_EMAIL_REGEX

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  validates :name, presence: true
  validates :var_type, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/controllers/code_classes_controller.rb
class CodeClassesController < ApplicationController
  before_action :set_code_class, only: [:show, :edit, :update, :destroy]

  # GET /code_classes
  # GET /code_classes.json
  def index
    filter_project_id = params[:filter_project] || current_project_id
    
    # filter_namespace_id could remain nil, that is fine.  CodeClass.by_project_and_namespace can handle that.
    filter_namespace_id   = nil
    filter_namespace_name = params[:filter_namespace]
    if filter_namespace_name
      ns = CodeNamespace.find_by_name filter_namespace_name
      filter_namespace_id = ns.id if ns
    end
      
    @code_classes = CodeClass.by_project_and_namespace( filter_project_id, filter_namespace_id )
  end

  # GET /code_classes/1
  # GET /code_classes/1.json
  def show
  end

  # GET /code_classes/new
  def new
    @code_class = CodeClass.new
  end

  # GET /code_classes/1/edit
  def edit
  end

  # POST /code_classes
  # POST /code_classes.json
  def create
    @code_class = CodeClass.new(code_class_params)

    respond_to do |format|
      if @code_class.save
        format.html { redirect_to @code_class, notice: 'Code class was successfully created.' }
        format.json { render :show, status: :created, location: @code_class }
      else
        format.html { render :new }
        format.json { render json: @code_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_classes/1
  # PATCH/PUT /code_classes/1.json
  def update
    respond_to do |format|
      if @code_class.update(code_class_params)
        format.html { redirect_to @code_class, notice: 'Code class was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_class }
      else
        format.html { render :edit }
        format.json { render json: @code_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_classes/1
  # DELETE /code_classes/1.json
  def destroy
    @code_class.destroy
    respond_to do |format|
      format.html { redirect_to code_classes_url, notice: 'Code class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_class
      @code_class = CodeClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_class_params
      params.require(:code_class).permit(:name, :ancestors, :code_file_id, :line)
    end
end

app/helpers/code_classes_helper.rb
module CodeClassesHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/code_classes/_form.html.erb
<%= form_for(@code_class) do |f| %>
  <% if @code_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_class.errors.count, "error") %> prohibited this code_class from being saved:</h2>

      <ul>
      <% @code_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ancestors %><br>
    <%= f.text_field :ancestors %>
  </div>
  <div class="field">
    <%= f.label :code_file_id %><br>
    <%= f.text_field :code_file_id %>
  </div>
  <div class="field">
    <%= f.label :line %><br>
    <%= f.number_field :line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_classes/edit.html.erb
<h1>Editing Code Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_class %> |
<%= link_to 'Back', code_classes_path %>

app/views/code_classes/index.html.erb
<h1 class="clarity-h1">
  <%= fa_icon( "object-group" )%> All Classes</h1>
<!--<div class="clarity-detail-box"></div>-->
<!--<p id="notice"><%= notice %></p>-->
 
<%= form_for CodeClass.new, html: {id: "classes-index-namespace-search-form", class: "form-horizontal"} do |f| %>
<div class="clarity-detail-box row">
    <div class="col-md-8">
			<%= f.label "Filter by namespace:", style: "margin-top:6px;" %>
			<%= f.collection_select :code_namespace_id, CodeNamespace.all, :id, :name, {include_blank: true}, style: "margin-bottom:10px;", class: "form-control" %> 
    </div>
    <div class="col-md-4">	
		  <%= f.submit "Filter", style: "margin-top:28px;", class: "btn btn-primary"		 %>
      <button id="filter-by-namespace-reset" style="margin-top:28px;" class="btn btn-primary">Reset</button>
		</div>
</div>
<% end %>    
 
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th>Ancestors</th>
      <th>Code file</th>
      <th>Namespace</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @code_classes.each do |code_class| %>
      <tr>
        <td><%= link_to code_class.name, code_class %></td>
        <td><%= code_class.code_file.project.name %></td>
        <td><%= code_class.ancestors %></td>
        <td><%= code_class.code_file.name %></td>
        <td><%= code_class.code_namespace.name %></td>
        <td><%= link_to 'Show', code_class_path(code_class), class: "btn btn-info btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/code_classes/new.html.erb
<h1>New Code Class</h1>

<%= render 'form' %>

<%= link_to 'Back', code_classes_path %>

app/views/code_classes/show.html.erb
<h1 class="clarity-h1"><%= image_tag "f_class2.png", size: "32", class: "element-icon" %> Class:  <%= @code_class.name %></h1>
<!--<p id="notice"><%= notice %></p>-->
<div class="clarity-detail-box">
<p>
  <strong>Ancestors:</strong>
  <%= @code_class.ancestors %>
</p>

<p>
  <strong>Code file:</strong>
  <%= link_to @code_class.code_file.path, code_file_path(@code_class.code_file) %>
  <%= link_to "Show", code_file_path(@code_class.code_file), class: "btn btn-info btn-xs" %>
</p>

<p>
  <strong>Namespace:</strong>
  <%= @code_class.code_namespace.name %>
</p>

<p>
  <strong>Line:</strong>
  <%= @code_class.line %>
</p>
</div>

<h2 class="clarity-h2">Data Members:</h2>
<ul>
<% @code_class.variables.each do |v| %>
    <li><%= v.name %></li>
<% end %>
</ul>

<h2 class="clarity-h2">Methods:</h2>
<ul>
<% @code_class.code_methods.each do |m| %>
    <%= m.decorate.list_item %>
<% end %>
</ul>

<!--<%#= link_to 'Edit', edit_code_class_path(@code_class) %> |
<%#= link_to 'Back', code_classes_path %>-->