config/routes.rb
Rails.application.routes.draw do
  resources :code_namespaces, only: [:show, :index]
  resources :folders, only: [:show]
  
  # resources :impl_calls
  # resources :preprocessor_lines
  # resources :variables
  resources :code_methods
  # resources :structures
  resources :code_classes, path: "classes"
  resources :code_files
  
  resources :projects do
    resources :display_boxes, only: [:index]
    resources :display_box_links, only: [:index]
  end
  
  resources :users
  
  root "welcome#index"
  
end

app/models/code_class.rb
class CodeClass < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many   :code_methods
  has_many   :variables
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_file.rb
class CodeFile < ActiveRecord::Base
  belongs_to :project
  belongs_to :folder
  has_many   :code_methods, dependent: :destroy
  has_many   :variables, dependent: :destroy
  has_many   :code_classes, dependent: :destroy
  
  validates :name, presence: true
  validates :path, presence: true
  validates :project_id, presence: true
end

app/models/code_method.rb
class CodeMethod < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many :impl_calls, dependent: :destroy, foreign_key: "caller_id"
  has_many :method_calls, through: :impl_calls,  source: :called
  
  has_many :inverse_callings, dependent: :nullify, class_name: "ImplCall", foreign_key: "called_id"  
  has_many :called_by, through: :inverse_callings, source: :caller
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :impl_start, numericality: {greater_than_or_equal_to: 1 }
  validates :impl_end,   numericality: {greater_than_or_equal_to: 1 }
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_namespace.rb
class CodeNamespace < ActiveRecord::Base

belongs_to :project

end

app/models/display_box.rb
class DisplayBox < ActiveRecord::Base
  belongs_to :folder
  
  # has_many :linked_boxes, dependent: :destroy, foreign_key: "parent_id"
  # has_many :children, through: :linked_boxes,  source: :display_box
  
  # has_many :inverse_ownerships, dependent: :nullify, class_name: "DisplayBoxLine", foreign_key: "display_box_id"  
  # has_many :linked_by, through: :inverse_ownerships, source: :parent
end

app/models/display_box_line.rb
class DisplayBoxLine < ActiveRecord::Base
   # belongs_to :parent, class_name: "DisplayBox"
   # belongs_to :display_box, class_name: "DisplayBox"
end

app/models/display_box_link.rb
class DisplayBoxLink < ActiveRecord::Base
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :projects
  
  has_many :sub_folders, dependent: :destroy, foreign_key: "parent_id"
  has_many :children, through: :sub_folders,  source: :folder
  
  has_many :inverse_ownerships, dependent: :nullify, class_name: "SubFolder", foreign_key: "folder_id"  
  has_many :owned_by, through: :inverse_ownerships, source: :parent
  
  	
  has_many :code_files,  dependent: :nullify
  has_one  :display_box, dependent: :nullify
  
  
  def contained_files_alphabetically 
    code_files.order(:name)
  end
end

app/models/impl_call.rb
class ImplCall < ActiveRecord::Base
	belongs_to :caller, class_name: "CodeMethod"
	belongs_to :called, class_name: "CodeMethod"
	
end

app/models/preprocessor_line.rb
class PreprocessorLine < ActiveRecord::Base
  belongs_to :code_file
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :user_projects, dependent: :nullify
  has_many :contributing_users, through: :user_projects, source: :user
  
  has_many :code_files,      dependent: :destroy
  has_many :folders,         dependent: :destroy
  has_many :code_namespaces, dependent: :destroy
  has_many :code_classes,    dependent: :destroy 
  has_many :code_methods,    dependent: :destroy 
  has_many :variables,       dependent: :destroy 
  
  validates :name,      presence: true#, uniqueness: true
  validates :root_path, presence: true#, uniqueness: true

end

app/models/structure.rb
class Structure < ActiveRecord::Base
  belongs_to :code_file
end

app/models/sub_folder.rb
class SubFolder < ActiveRecord::Base
  belongs_to :parent, class_name: "Folder"
  belongs_to :folder, class_name: "Folder"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password  
	
	has_many :user_projects, dependent: :nullify
	has_many :projects, through: :user_projects, source: :project 
	
	validates :first_name, presence: true

    # password must be there and password_confirmation has to match
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates	:email, presence: true, uniqueness: true,
						format: VALID_EMAIL_REGEX

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  validates :name, presence: true
  validates :var_type, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/controllers/code_files_controller.rb
class CodeFilesController < ApplicationController
  before_action :set_code_file, only: [:show, :edit, :update, :destroy]

  # GET /code_files
  # GET /code_files.json
  def index
    @code_files = CodeFile.all
  end

  # GET /code_files/1
  # GET /code_files/1.json
  def show
    @display_all = (params[:display] == "all")
  end

  # GET /code_files/new
  def new
    @code_file = CodeFile.new
  end

  # GET /code_files/1/edit
  def edit
  end

  # POST /code_files
  # POST /code_files.json
  def create
    @code_file = CodeFile.new(code_file_params)

    respond_to do |format|
      if @code_file.save
        format.html { redirect_to @code_file, notice: 'Code file was successfully created.' }
        format.json { render :show, status: :created, location: @code_file }
      else
        format.html { render :new }
        format.json { render json: @code_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_files/1
  # PATCH/PUT /code_files/1.json
  def update
    respond_to do |format|
      if @code_file.update(code_file_params)
        format.html { redirect_to @code_file, notice: 'Code file was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_file }
      else
        format.html { render :edit }
        format.json { render json: @code_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_files/1
  # DELETE /code_files/1.json
  def destroy
    @code_file.destroy
    respond_to do |format|
      format.html { redirect_to code_files_url, notice: 'Code file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_file
      @code_file = CodeFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_file_params
      params.require(:code_file).permit(:name, :path, :project_id)
    end
end

app/helpers/code_files_helper.rb
module CodeFilesHelper
	def get_code_for_file( file )
		f = FileReader.new
		lines = f.get_range_in_file( file.path ) #takes advantage of default arguments to get the entire file.
		
		output = String.new
		# NEWLINE = "\r\n"
		lines.each do |line|
			output += "#{line.line.r_just}#{line.text}\r\n"
		end
		output
	end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/code_files/_form.html.erb
<%= form_for(@code_file) do |f| %>
  <% if @code_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code_file.errors.count, "error") %> prohibited this code_file from being saved:</h2>

      <ul>
      <% @code_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/code_files/edit.html.erb
<h1>Editing Code File</h1>

<%= render 'form' %>

<%= link_to 'Show', @code_file %> |
<%= link_to 'Back', code_files_path %>

app/views/code_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Code Files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Path</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @code_files.each do |code_file| %>
      <tr>
        <td><%= code_file.name %></td>
        <td><%= code_file.path %></td>
        <td><%= code_file.project %></td>
        <td><%= link_to 'Show', code_file %></td>
        <td><%= link_to 'Edit', edit_code_file_path(code_file) %></td>
        <td><%= link_to 'Destroy', code_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code file', new_code_file_path %>

app/views/code_files/new.html.erb
<h1>New Code File</h1>

<%= render 'form' %>

<%= link_to 'Back', code_files_path %>

app/views/code_files/show.html.erb
<h1 class="clarity-h1"><span class="big-icon show-folder-heading-icon"><%= fa_icon("file-text-o")%></span> File: <%= @code_file.name %></h1>

<!--<p id="notice"><%= notice %></p>-->
<div class="clarity-detail-box">
  <div class="row">
    <div class="col-md-8">
      <p>
        <strong>Project:</strong>
        <%= @code_file.project.name %>
      </p>
      <p>
        <strong>Path:</strong>
        <%= @code_file.path %>
      </p>
      <ul>
        <% if @code_file.code_classes.any? %>
        <li><%= @code_file.code_classes.count %> class(es)</li>
        <%end%>
        <% if @code_file.code_methods.any? %>
        <li><%= @code_file.code_methods.count %> method(s)</li>
        <%end%>
        <% if @code_file.variables.any? %>
        <li><%= @code_file.variables.count %> variable(s)</li>
        <%end%>      
      </ul>
    </div>
    <div class="col-md-4">
      <% if @display_all %>
        <%= link_to "Hide code", code_file_path(@code_file), 
                  class: "btn btn-info", 
                  style: "float: right; margin-right: 15px;",
                  id:  "code-file-show-page-hide-code" 
                  %>      
      <% else %>
        <%= link_to "Display entire file", code_file_path(@code_file) + "?display=all#code-file-show-page-code-block", 
                  class: "btn btn-info", 
                  style: "float: right; margin-right: 15px;" 
                  %>
      <% end %>
    </div>
  </div>
</div>

<% if @code_file.code_classes.any? %>
<h2 class="clarity-h2">Classes:</h2>
<ul>
  <% @code_file.code_classes.each do |ccclass| %>
  <li><%= link_to ccclass.name, code_class_path( ccclass ) %></li>
  <%end%>
</ul>
<%end%>

<% if @code_file.code_methods.any? %>
<h2 class="clarity-h2">Methods:</h2>
<ul>
  <% @code_file.code_methods.each do |mmmethod| %>
  <li><%= link_to mmmethod.name, code_method_path( mmmethod ) %></li>
  <%end%>
</ul>
<%end%>

<% if @code_file.variables.any? %>
<h2 class="clarity-h2">Variables:</h2>
<ul>
  <% @code_file.variables.each do |vvvar| %>
  <li><%= vvvar.name %></li>
  <!--<li><%#= link_to vvvar.name, variable_path( vvvar ) %></li>-->
  <%end%>
</ul>
<%end%>   

<div id="code-file-show-page-code-block">
  <% if @display_all %>
  <h2 class="clarity-h2">Source Code:  <%= @code_file.name %></h2>
    <pre><code><%= get_code_for_file( @code_file ) %></code></pre>
  <% end %>   
</div>