config/routes.rb
Rails.application.routes.draw do
  resources :code_namespaces, only: [:show, :index]
  resources :folders, only: [:show]
  
  # resources :impl_calls
  # resources :preprocessor_lines
  # resources :variables
  resources :code_methods
  # resources :structures
  resources :code_classes, path: "classes"
  resources :code_files
  
  resources :projects do
    resources :display_boxes, only: [:index]
    resources :display_box_links, only: [:index]
  end
  
  resources :users
  
  root "welcome#index"
  
end

app/models/code_class.rb
class CodeClass < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many   :code_methods
  has_many   :variables
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_file.rb
class CodeFile < ActiveRecord::Base
  belongs_to :project
  belongs_to :folder
  has_many   :code_methods, dependent: :destroy
  has_many   :variables, dependent: :destroy
  has_many   :code_classes, dependent: :destroy
  
  validates :name, presence: true
  validates :path, presence: true
  validates :project_id, presence: true
end

app/models/code_method.rb
class CodeMethod < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  has_many :impl_calls, dependent: :destroy, foreign_key: "caller_id"
  has_many :method_calls, through: :impl_calls,  source: :called
  
  has_many :inverse_callings, dependent: :nullify, class_name: "ImplCall", foreign_key: "called_id"  
  has_many :called_by, through: :inverse_callings, source: :caller
  
  validates :name, presence: true
  validates :code_file_id, presence: true
  validates :impl_start, numericality: {greater_than_or_equal_to: 1 }
  validates :impl_end,   numericality: {greater_than_or_equal_to: 1 }
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/models/code_namespace.rb
class CodeNamespace < ActiveRecord::Base

belongs_to :project

end

app/models/display_box.rb
class DisplayBox < ActiveRecord::Base
  belongs_to :folder
  
  # has_many :linked_boxes, dependent: :destroy, foreign_key: "parent_id"
  # has_many :children, through: :linked_boxes,  source: :display_box
  
  # has_many :inverse_ownerships, dependent: :nullify, class_name: "DisplayBoxLine", foreign_key: "display_box_id"  
  # has_many :linked_by, through: :inverse_ownerships, source: :parent
end

app/models/display_box_line.rb
class DisplayBoxLine < ActiveRecord::Base
   # belongs_to :parent, class_name: "DisplayBox"
   # belongs_to :display_box, class_name: "DisplayBox"
end

app/models/display_box_link.rb
class DisplayBoxLink < ActiveRecord::Base
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  belongs_to :projects
  
  has_many :sub_folders, dependent: :destroy, foreign_key: "parent_id"
  has_many :children, through: :sub_folders,  source: :folder
  
  has_many :inverse_ownerships, dependent: :nullify, class_name: "SubFolder", foreign_key: "folder_id"  
  has_many :owned_by, through: :inverse_ownerships, source: :parent
  
  	
  has_many :code_files,  dependent: :nullify
  has_one  :display_box, dependent: :nullify
  
  
  def contained_files_alphabetically 
    code_files.order(:name)
  end
end

app/models/impl_call.rb
class ImplCall < ActiveRecord::Base
	belongs_to :caller, class_name: "CodeMethod"
	belongs_to :called, class_name: "CodeMethod"
	
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :user_projects, dependent: :nullify
  has_many :contributing_users, through: :user_projects, source: :user
  
  has_many :code_files,      dependent: :destroy
  has_many :folders,         dependent: :destroy
  has_many :code_namespaces, dependent: :destroy
  has_many :code_classes,    dependent: :destroy 
  has_many :code_methods,    dependent: :destroy 
  has_many :variables,       dependent: :destroy 
  
  validates :name,      presence: true#, uniqueness: true
  validates :root_path, presence: true#, uniqueness: true

end

app/models/structure.rb
class Structure < ActiveRecord::Base
  belongs_to :code_file
end

app/models/sub_folder.rb
class SubFolder < ActiveRecord::Base
  belongs_to :parent, class_name: "Folder"
  belongs_to :folder, class_name: "Folder"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password  
	
	has_many :user_projects, dependent: :nullify
	has_many :projects, through: :user_projects, source: :project 
	
	validates :first_name, presence: true

    # password must be there and password_confirmation has to match
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	
	validates	:email, presence: true, uniqueness: true,
						format: VALID_EMAIL_REGEX

end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  belongs_to :code_file
  belongs_to :code_class
  belongs_to :code_namespace
  belongs_to :project 
  
  validates :name, presence: true
  validates :var_type, presence: true
  validates :code_file_id, presence: true
  validates :line, numericality: {greater_than_or_equal_to: 1 }
  
  
  def self.by_project_and_namespace( project_id, namespace_id = nil )
    if( namespace_id )
      where(project_id: project_id, code_namespace_id: namespace_id ).order(:name)
    else
      where(project_id: project_id ).order(:name)
    end
  end
  
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav">
      <li><a href="<%=root_path%>">
        <span><%= image_tag "f_home_icon64.png", size: "32" %></span>
        <!--<span style=>Clarity</span>-->
      </a></li>
        <% if !current_project_id %>
        <li><%= link_to "Projects", projects_path %></li>
        <% else %>
        <!--<li><span class="label label-success">Project:  <%= current_project_name %></span></li>-->
        <li><%= link_to "All Projects", projects_path %></li>
        <li><%= link_to "Project: " + current_project_name, project_path(current_project_id) %></li>
        <li><%= link_to "All Classes", code_classes_path, id: "all-classes-link" %></li>
        <li><%= link_to "All Namespaces", code_namespaces_path %></li>
        <% end %>
      </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "[]", root_path + "#home-page-future" %> </li>
      <!--<%# if user_signed_in? %>
        <li>Hello <%#= current_user.first_name %></li>
        <li><%#= link_to "Sign out", sessions_path, method: :delete %></li>
      <%# else %>
        <li><%#= link_to "Sign in", new_session_path %></li>
        <li><%#= link_to "Sign up", new_user_path %></li>
      <%# end %>-->
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clarity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <%= render "/layouts/nav" %>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>